os:
  - osx
  - linux
  - windows
dist: bionic

language: node_js
node_js:
  - lts/*
  - node

cache:
  - cargo
  - npm

before_install:
  # Install Rust and Cargo
  - curl https://sh.rustup.rs -sSf > /tmp/rustup.sh
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then export RUSTUP_OPTIONS="--default-host x86_64-pc-windows-msvc --default-toolchain stable-x86_64-pc-windows-msvc"; fi
  - sh /tmp/rustup.sh -y $RUSTUP_OPTIONS
  - export PATH="$HOME/.cargo/bin:$PATH"
  - source "$HOME/.cargo/env" || true
  - rustc --version
  - cargo --version
  # Install NPM packages
  - node -v
  - npm -v
  - npm -g install neon-cli
  - npm -g install yarn
  - yarn -v

install:
  - yarn

script:
  - yarn workspaces run test
  - yarn workspaces run fmt
  - yarn workspaces run lint
  - git diff --exit-code
  - if [ -n "$TRAVIS_TAG" ]; then rm -rf packages/indexer/build; yarn workspace @ckb-lumos/indexer run package; fi

jobs:
  include:
    - os: osx
      script:
        - if [ -n "$TRAVIS_TAG" ]; then rm -rf packages/indexer/build; yarn workspace @ckb-lumos/indexer run package-for-electron; fi
    - os: linux
      dist: bionic
      script:
        - if [ -n "$TRAVIS_TAG" ]; then rm -rf packages/indexer/build; yarn workspace @ckb-lumos/indexer run package-for-electron; fi
    - os: windows
      script:
        - if [ -n "$TRAVIS_TAG" ]; then rm -rf packages/indexer/build; yarn workspace @ckb-lumos/indexer run package-for-electron; fi

deploy:
  - provider: releases
    skip_cleanup: true
    on:
      tags: true
    api_key: "$GITHUB_TOKEN"
    file_glob: true
    file:
      - "packages/indexer/build/stage/${TRAVIS_TAG}/*"
