os:
  - osx
  - linux
  - windows
dist: bionic

language: node_js
node_js:
  - 12
  - 13

cache:
  - cargo
  - npm

before_install:
  # Install Rust and Cargo
  - curl https://sh.rustup.rs -sSf > /tmp/rustup.sh
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then export RUSTUP_OPTIONS="--default-toolchain stable-x86_64-pc-windows-msvc"; fi
  - sh /tmp/rustup.sh -y $RUSTUP_OPTIONS
  - export PATH="$HOME/.cargo/bin:$PATH"
  - source "$HOME/.cargo/env" || true
  - rustc --version
  - cargo --version
  # Install NPM packages
  - node -v
  - npm -v
  - npm -g install neon-cli
  - npm -g install lerna
  - lerna bootstrap

script:
  - lerna run test
  - lerna run fmt
  - git diff --exit-code
  - if [ -n "$TRAVIS_TAG" ]; then cd packages/indexer; rm -rf build; npm run package; fi

deploy:
  - provider: releases
    skip_cleanup: true
    on:
      tags: true
    api_key: "$GITHUB_TOKEN"
    file_glob: true
    file:
      - "build/stage/${TRAVIS_TAG}/*"
