# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - "*"
  tags:
    include:
      - "*"

variables:
  LUMOS_NODE_RUNTIME_VERSION: 9.0.2

jobs:
  - job: LinuxBuild
    pool:
      vmImage: "ubuntu-20.04"
    steps:
      - template: devtools/azure/linux-dependencies.yml
        parameters:
          rustup_toolchain: "stable"
          node_version: "14.x"
          ckb_indexer_version: "0.2.2"
      - template: devtools/azure/install-npm-dependencies.yml
      - template: devtools/azure/start-indexer/start-linux-osx-test-evn.yml
      - template: devtools/azure/ci.yml
      - script: |
          yarn run docs
        displayName: "Linux specific tests"
      - template: devtools/azure/ci-completion.yml
      - task: PublishCodeCoverageResults@1
        inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: "$(System.DefaultWorkingDirectory)/**/*coverage.xml"
          reportDirectory: "$(System.DefaultWorkingDirectory)/**/coverage"
  - job: OSXBuild
    pool:
      vmImage: "macOS-10.15"
    steps:
      - template: devtools/azure/osx-dependencies.yml
        parameters:
          rustup_toolchain: "stable"
          node_version: "14.x"
          ckb_indexer_version: "0.2.2"
      - template: devtools/azure/install-npm-dependencies.yml
      - template: devtools/azure/start-indexer/start-linux-osx-test-evn.yml
      - template: devtools/azure/ci.yml
      - template: devtools/azure/ci-completion.yml
  - job: WindowsBuild
    pool:
      vmImage: "vs2017-win2016"
    steps:
      - template: devtools/azure/windows-dependencies.yml
        parameters:
          rustup_toolchain: "stable"
          node_version: "14.x"
          ckb_indexer_version: "0.2.2"
      - template: devtools/azure/install-npm-dependencies.yml
      - template: devtools/azure/start-indexer/start-windows-test-env.yml
      - template: devtools/azure/ci.yml
      - template: devtools/azure/ci-completion.yml
  - job: LinuxRelease
    dependsOn: LinuxBuild
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags'))
    pool:
      vmImage: "ubuntu-20.04"
    steps:
      - template: devtools/azure/linux-dependencies.yml
        parameters:
          rustup_toolchain: "stable"
          node_version: "14.x"
          ckb_indexer_version: "0.2.2"
      - script: |
          npm -g install neon-cli
        displayName: "Install neon-cli"
      - task: GithubRelease@1
        displayName: "Upload release file"
        inputs:
          action: edit
          gitHubConnection: lumos_release
          repositoryName: nervosnetwork/lumos
          tag: $(Build.SourceBranchName)
          assetUploadMode: "replace"
          assets: "packages/indexer/build/stage/$(Build.SourceBranchName)/*"
  - job: OSXRelease
    dependsOn: OSXBuild
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags'))
    pool:
      vmImage: "macOS-10.15"
    steps:
      - template: devtools/azure/osx-dependencies.yml
        parameters:
          rustup_toolchain: "stable"
          node_version: "14.x"
          ckb_indexer_version: "0.2.2"
      - script: |
          npm -g install neon-cli
        displayName: "Install neon-cli"
      - task: GithubRelease@1
        displayName: "Upload release file"
        inputs:
          action: edit
          gitHubConnection: lumos_release
          repositoryName: nervosnetwork/lumos
          tag: $(Build.SourceBranchName)
          assetUploadMode: "replace"
          assets: "packages/indexer/build/stage/$(Build.SourceBranchName)/*"
  - job: WindowsRelease
    dependsOn: WindowsBuild
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags'))
    pool:
      vmImage: "vs2017-win2016"
    steps:
      - template: devtools/azure/windows-dependencies.yml
        parameters:
          rustup_toolchain: "stable"
          node_version: "14.x"
          ckb_indexer_version: "0.2.2"
      - script: |
          npm -g install neon-cli
        displayName: "Install neon-cli"
      - script: |
          rm -rf packages/indexer/build
        displayName: "Remove previous built files"
      - script: |
          yarn
        displayName: "Install dependencies"
      - task: GithubRelease@1
        displayName: "Upload release file"
        inputs:
          action: edit
          gitHubConnection: lumos_release
          repositoryName: nervosnetwork/lumos
          tag: $(Build.SourceBranchName)
          assetUploadMode: "replace"
          assets: "packages/indexer/build/stage/$(Build.SourceBranchName)/*"
