[package]
name = "lumos-indexer"
version = "0.1.0"
authors = ["Xuejie Xiao <xxuejie@gmail.com>"]
license = "MIT"
build = "build.rs"
edition = "2018"
exclude = ["artifacts.json", "index.node"]

[lib]
name = "lumos_indexer"
crate-type = ["cdylib"]

[build-dependencies]
neon-build = "0.4.0"

[dependencies]
ckb-indexer = { git = "https://github.com/xxuejie/ckb-indexer", rev = "f7d039c" }
ckb-types = "=0.100.0-rc2"
ckb-jsonrpc-types = "=0.100.0-rc2"
env_logger = "0.7.1"
futures = "0.1"
jsonrpc-core = "14.0"
jsonrpc-core-client = { version = "14.0", features = ["http", "tls"] }
jsonrpc-derive = "14.0"
hyper = "0.12"
log = "0.4.8"
neon = { version = "0.4.0", features = ["event-handler-api"] }
num_cpus = "1.13.0"
serde_json = "1.0.59"
lazysort = "0.2.1"

[patch.crates-io]
neon-sys = { git = "https://github.com/xxuejie/neon", rev = "6e246f2" }
