[package]
name = "lumos-indexer"
version = "0.1.0"
authors = ["Xuejie Xiao <xxuejie@gmail.com>"]
license = "MIT"
edition = "2018"
exclude = ["artifacts.json", "index.node"]

[lib]
name = "lumos_indexer"
crate-type = ["cdylib"]

[dependencies]
ckb-indexer = { git = "https://github.com/quake/ckb-indexer", tag = "v0.1.6" }
ckb-jsonrpc-types = { git = "https://github.com/nervosnetwork/ckb", tag = "v0.31.0-pre1" }
ckb-types = { git = "https://github.com/nervosnetwork/ckb", tag = "v0.31.0-pre1" }
env_logger = "0.7.1"
futures = "0.1"
jsonrpc-core = "14.0"
jsonrpc-core-client = { version = "14.0", features = ["http", "tls"] }
jsonrpc-derive = "14.0"
hyper = "0.12"
log = "0.4.8"
num_cpus = "1.13.0"
serde_json = "1.0.59"
lazysort = "0.2.1"
tokio = { version = "1.5.0", features = ["full"] }

[dependencies.neon]
version = "0.8.3"
default-features = false
features = ["napi-4", "event-queue-api"]
